# Generated by Django 5.0 on 2024-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMSapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_rental",
            field=models.DecimalField(
                db_column="total rental",
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="total rental",
            ),
        ),
    ]
